#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Mon Jan 21 22:11:48 IST 2019
apiSecret=bdebcb798e01ffb57f52c41a23f5521d960763b37afd7687c7964888107a8355
